
export const TRANSLATIONS = {
  EN: {
    title: "Optimedix",
    tagline: "Smart Retinal Health Screening",
    login: "Login",
    signup: "Sign Up",
    fullName: "Full Name",
    mobile: "Mobile Number",
    role: "Role",
    clinic: "Clinic/Hospital Name",
    district: "District",
    state: "State",
    dashboard: "Dashboard",
    registerPatient: "Register Patient",
    statistics: "Statistics",
    emergency: "Emergency Mode",
    analysis: "AI Analysis",
    refer: "Refer to Hospital",
    downloadReport: "Download Report",
    logout: "Logout",
    patientsScreened: "Patients Screened Today",
    positiveCases: "Positive Cases",
    referrals: "Referrals Sent",
  },
  HI: {
    title: "ऑप्टिमेडिक्स",
    tagline: "स्मार्ट रेटिनल स्वास्थ्य स्क्रीनिंग",
    login: "लॉगिन",
    signup: "साइन अप",
    fullName: "पूरा नाम",
    mobile: "मोबाइल नंबर",
    role: "भूमिका",
    clinic: "क्लीनिक/अस्पताल का नाम",
    district: "ज़िला",
    state: "राज्य",
    dashboard: "डैशबोर्ड",
    registerPatient: "रोगी पंजीकरण",
    statistics: "सांख्यिकी",
    emergency: "आपातकालीन मोड",
    analysis: "एआई विश्लेषण",
    refer: "अस्पताल भेजें",
    downloadReport: "रिपोर्ट डाउनलोड करें",
    logout: "लॉगआउट",
    patientsScreened: "आज स्क्रीनिंग किए गए मरीज़",
    positiveCases: "पॉजिटिव केस",
    referrals: "भेजे गए रेफरल",
  }
};
